### ISSUE TITLE
List unsupported error in setDefValues

### ISSUE THREAD

**Issue by Lia-LV** [Osiris-Team/Dyml#28]
```
public List<String> get(String path, String[] defaultValue, int topLineBreaks, String... comments) throws NotLoadedException, IllegalKeyException {
        YamlSection yamlSection;
        if (isPathSplitRequired(path)) {
            yamlSection = this.config.put(pathSplit(path)).setDefValues(defaultValue).setCountTopLineBreaks(topLineBreaks).setComments(comments);
        } else {
            yamlSection = this.config.put(path).setDefValues(defaultValue).setCountTopLineBreaks(topLineBreaks).setComments(comments);
        }
        System.out.println(yamlSection.asStringList().toString());

        return isValueNull(yamlSection) ? List.of(defaultValue) : yamlSection.asStringList();
    }
```

I'm using the same code as above. If I put parameter(defaultValue) in setDefValues, it does not work properly(Unconditional initialization, asStringList() return empty list etc...). Can you check about this situation? (If I enter a value directly instead of the defaultValue parameter, it works properly, The defaultValue parameter is new String[]{"foo", "bar"})

EDIT : The "`List<SmartString>`" parameter is not working properly either.

**Comment by Osiris-Team** [comment]
@Lia-LV true, just released a fix. checkout 9.7.1

**Comment by Lia-LV** [comment]
@Osiris-Team I confirmed that the asStringList is working properly. But setDefValues(String[] or List<>...) still resets the value. Is there something wrong with my settings?

**Comment by Osiris-Team** [comment]
@Lia-LV what do you mean by that? setDefValues() will set the default values and override it. If the regular values list is empty the default values list will be used.

**Comment by Lia-LV** [comment]
@Osiris-Team Sorry, I'm a little late trying to find the cause because it seems to only work under certain conditions. 
setDefValues() always resets the value if a colon( : ) is included, only in the List type. It's okay if the colon is stuck with another character, but it's a problem if colon is floating alone.

**Comment by Osiris-Team** [comment]
@Lia-LV values should not contain columns

**Comment by Lia-LV** [comment]
@Osiris-Team It worked well in the case of TestKey1, so I thought it would work well in the case of TestKey3. 
Then, should I not use it in the case of TestKey1?

**Comment by Osiris-Team** [comment]
@Lia-LV Keys are identified by having a spaceafter the colon thus the following is valid "not:a:key" "key "

**Comment by Lia-LV** [comment]
@Osiris-Team I understand. I think all the problems are solved. Thank you always.

**Comment by Osiris-Team** [comment]
Good to hear that :)
